FROM python:3.6
MAINTAINER Borodin Gregory <grihabor@mail.ru>

RUN pip3 install --no-cache-dir \
        numpy==1.12 \
        blessings==1.6 \
        requests==2.17 \
        flask==0.12 \
        python-dateutil
